name: lyonheart
favicon: null
layout_spectrum: 0.004590120632201433
typography_spectrum: 0.5667761391960084
title: unschooling portfolio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0f171f'
    - '#534f55'
    - '#abc6e8'
    - '#af7871'
  brandStrength: 0.908724176697433
  lightness: 0.4122068574652076
  saturation: 0.232736777048558
  rhythmicContrast: 0.18212926294654608
purpose: []
